config_path : https://github.com/acl-org/acl-style-files/archive/refs/heads/master.zip
folder_path : acl-style-files-master
main_file: latex/acl_latex

# Mark for tmr : Directory issue --> Maybe parsing the path