name: Update the anthology
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download the file
        run: |
          curl -L https://aclanthology.org/anthology.bib.gz -o anthology.bib.gz
          gzip -d anthology.bib.gz

      # Maybe need some if? - But would it be a waste of time to compare?
      - name: Compare with the anthology main
        run: |
          cp -f anthology.bib 99_anthology.bib

      # Commit and Push the file. Not sure if this is correct or not
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
          git push origin main