name: Update the anthology
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Download the file
        run: |
          curl -L https://aclanthology.org/anthology.bib.gz -o anthology.bib.gz
          gzip -d anthology.bib.gz

      # Maybe need some if? - But would it be a waste of time to compare?
      - name: Compare with the anthology main
        run: |
          cp -f anthology.bib 99_anthology.bib