# updating main branch

on:
  push:
    branches:
      - verify

jobs:
  cache-latex:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "ghcr.io/hspaans/latexmk-action:1"
          cache-from: type=gha
          cache-to: type=gha,mode=max
