name: Compile to LaTeX PDF
run-name: it's a work in progress
on: [push]
jobs:
  Compile-To-PDF:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: main.tex