name: List conference branches

on:
  push:

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: List all branches
        id: list-branches
        run: |
          BRANCHES=$(git branch -r | grep -v '\->' | grep -v 'origin/HEAD' | sed 's|origin/||')
          echo "::set-output name=branches::${BRANCHES}"

      - name: Set matrix
        id: set-matrix
        run: |
          BRANCHES=${{ steps.list-branches.outputs.branches }}
          BRANCH_ARRAY=($(echo $BRANCHES | tr " " "\n"))
          MATRIX=$(printf "%s\n" "${BRANCH_ARRAY[@]}" | jq -R . | jq -s .)
          echo "::set-output name=matrix::${MATRIX}"
