name: Copy and Replace

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      folder-path:
        required: true
        type: string
  push:
    branches:
      - verify

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and extract directory
        run: |
          curl -L ${{ inputs.config-path }} -o initial.tar.gz
          tar -xf initial.tar.gz
          rm initial.tar.gz
          mv author-kit-CVPR2024-v2/ CVPR-2024-main
      # How do we know the folder name here?

      # - name: Clone ml-paper-template-testing
      #   run: |
      #     git clone git@github.com:jqhc/ml-paper-template-testing.git
          
      # - name: Copy contents from CVPR 2024
      #   run: |
      #     cp -r CVPR-2024-main/sec ml-paper-template-testing/
      #     cp -f CVPR-2024-main/main.tex ml-paper-template-testing/
      #     cp -f CVPR-2024-main/cvpr.sty ml-paper-template-testing/cvpr.sty

      # - name: Rename original cvpr conference file 
      #   run: | 
      #     mv CVPR-2024-main/main.tex CVPR-2024-main/cvpr_template.tex
      #     cd CVPR-2024-main

      - name: Render PDF cvpr2024
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: -cd ./CVPR-2024-main/main.tex

      # - name: Rename original ml-paper conference file 
      #   run: |
      #     cd ..
      #     mv ml-paper-template/main.tex ml-paper-template/ml_template.tex
      #     cd ml-paper-template
      
      # - name: Render PDF ml-paper
      #   uses: hspaans/latexmk-action@v1
      #   with:
      #     format: pdf
      #     filename: -cd ./ml-paper-template/main.tex  

      - name: Convert PDF to PPM
        run: |
          pdftoppm -jpeg -r 300 CVPR-2024-main/cvpr_template.pdf output
          pdftoppm -jpeg -r 300 ml-paper-template/cvpr_template.pdf output_temp

      # - name: Compare images
      #   run: |
      #     for i in $(seq 1 5); do
      #       magick compare output-${i}.jpg output_temp-${i}.jpg diff_${i}.jpg
      #     done


